prefix aiiso:   <http://purl.org/vocab/aiiso/schema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?dept ?gcount ?label
{
    {
        SELECT DISTINCT ?dept (COUNT(DISTINCT ?person) AS ?gcount)
        {
            GRAPH ?v1
            {
                ?dept  rdf:type  aiiso:Institution .
                ?dept foaf:member ?person .
            }
        }
        GROUP BY ?dept
    }
    GRAPH ?v2
    {
        ?dept rdfs:label ?label .
    }
}
ORDER BY ?label