prefix dc: <http://purl.org/dc/terms/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# We can do this using SAMPLE, but not implemented in arnos yet
select distinct ?type ?scount ?label
{
    { select ?type (count(distinct ?s) as ?scount) { graph ?g1 { ?s dc:type ?type } } group by ?type }
    graph ?g2 { ?type rdfs:label ?label }
}
